#!/bin/bash
#SBATCH --job-name=julia_update
#SBATCH --partition=gpu_a100
#SBATCH --time=00:20:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus-per-node=1
#SBATCH --output=update_julia.out

module load 2023
module load juliaup/1.14.5-GCCcore-12.3.0
export JULIA_NUM_PRECOMPILE_TASKS=18
srun --unbuffered julia --project -t auto -e 'using Pkg; Pkg.instantiate(); Pkg.update(); Pkg.resolve()'
